    ADServerRole:
        Type: AWS::IAM::Role
        Properties:
            Policies:
            -   PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Action:
                        - s3:GetObject
                        Resource:
                            Fn::Sub: arn:aws:s3:::${DSS3BucketName}/${DSS3KeyPrefix}/*
                        Effect: Allow
                PolicyName: aws-deploy-sample-s3-policy
            -   PolicyName: AD-SSM-Parameters
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Effect: Allow
                        Action:
                        - ssm:PutParameter
                        - ssm:DeleteParameter
                        - ssm:GetParameter
                        Resource:
                            Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*
                    -   Effect: Allow
                        Action:
                        - ssm:DescribeParameters
                        Resource: '*'
            Path: /
            ManagedPolicyArns:
            - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
            AssumeRolePolicyDocument:
                Statement:
                -   Action:
                    - sts:AssumeRole
                    Principal:
                        Service:
                        - ec2.amazonaws.com
                    Effect: Allow
                Version: 2012-10-17





    EC2Role:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                -   Effect: Allow
                    Principal:
                        Service:
                        - ec2.amazonaws.com
                    Action:
                    - sts:AssumeRole
            Path: /
            Policies:
            -   PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Action:
                        - s3:GetObject
                        Resource:
                            Fn::Sub: arn:aws:s3:::${DSS3BucketName}/${DSS3KeyPrefix}/*
                        Effect: Allow
                PolicyName: aws-deploy-sample-s3-policy
            -   PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Action:
                        - s3:GetObject
                        Resource:
                            Fn::Sub: arn:aws:s3:::${SetupKitsS3BucketName}/${SetupKitsS3KeyPrefix}/*
                        Effect: Allow
                PolicyName: aws-setup-kits-s3-policy
            -   PolicyName: SSM-Parameters-DomainJoin
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Effect: Allow
                        Action:
                        - ssm:GetParameter
                        - ssm:GetParameters
                        Resource:
                            Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${NamePrefix}/${DomainAdminUserName}
                    -   Effect: Allow
                        Action:
                        - ssm:DescribeParameters
                        Resource: '*'
                    -   Effect: Allow
                        Action:
                        - kms:Decrypt
                        Resource:
                            Fn::Sub: arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ssm
            -   PolicyName: SSM-Parameters-PIAssetFramework
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Effect: Allow
                        Action:
                        - ssm:GetParameter
                        - ssm:GetParameters
                        Resource:
                            Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${NamePrefix}/${PIAFServiceAccountName}
                    -   Effect: Allow
                        Action:
                        - ssm:DescribeParameters
                        Resource: '*'
                    -   Effect: Allow
                        Action:
                        - kms:Decrypt
                        Resource:
                            Fn::Sub: arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ssm
    EC2RoleInstanceProfile:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Path: /
            Roles:
            -   Ref: EC2Role




Resources:
    EC2Role:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                -   Effect: Allow
                    Principal:
                        Service:
                        - ec2.amazonaws.com
                    Action:
                    - sts:AssumeRole
            Path: /
            Policies:
            -   PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Action:
                        - s3:GetObject
                        Resource:
                            Fn::Sub: arn:aws:s3:::${DSS3BucketName}/${DSS3KeyPrefix}/*
                        Effect: Allow
                PolicyName: aws-deploy-sample-s3-policy
            -   PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Action:
                        - s3:GetObject
                        Resource:
                            Fn::Sub: arn:aws:s3:::${SetupKitsS3BucketName}/${SetupKitsS3KeyPrefix}/*
                        Effect: Allow
                PolicyName: aws-setup-kits-s3-policy
            -   PolicyName: SSM-Parameters-DomainJoin
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Effect: Allow
                        Action:
                        - ssm:GetParameter
                        - ssm:GetParameters
                        Resource:
                            Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${NamePrefix}/${DomainAdminUserName}
                    -   Effect: Allow
                        Action:
                        - ssm:DescribeParameters
                        Resource: '*'
                    -   Effect: Allow
                        Action:
                        - kms:Decrypt
                        Resource:
                            Fn::Sub: arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ssm
            -   PolicyName: SSM-Parameters-PIAnalytics
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Effect: Allow
                        Action:
                        - ssm:GetParameter
                        - ssm:GetParameters
                        Resource:
                            Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${NamePrefix}/${PIANServiceAccountName}
                    -   Effect: Allow
                        Action:
                        - ssm:DescribeParameters
                        Resource: '*'
                    -   Effect: Allow
                        Action:
                        - kms:Decrypt
                        Resource:
                            Fn::Sub: arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ssm
    EC2RoleInstanceProfile:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Path: /
            Roles:
            -   Ref: EC2Role






    EC2Role:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                -   Effect: Allow
                    Principal:
                        Service:
                        - ec2.amazonaws.com
                    Action:
                    - sts:AssumeRole
            Path: /
            Policies:
            -   PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Action:
                        - s3:GetObject
                        Resource:
                            Fn::Sub: arn:aws:s3:::${DSS3BucketName}/${DSS3KeyPrefix}/*
                        Effect: Allow
                PolicyName: aws-deploy-sample-s3-policy
            -   PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Action:
                        - s3:GetObject
                        Resource:
                            Fn::Sub: arn:aws:s3:::${SetupKitsS3BucketName}/${SetupKitsS3KeyPrefix}/*
                        Effect: Allow
                PolicyName: aws-setup-kits-s3-policy
            -   PolicyName: SSM-Parameters-DomainJoin
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Effect: Allow
                        Action:
                        - ssm:GetParameter
                        - ssm:GetParameters
                        Resource:
                            Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${NamePrefix}/${DomainAdminUserName}
                    -   Effect: Allow
                        Action:
                        - ssm:DescribeParameters
                        Resource: '*'
                    -   Effect: Allow
                        Action:
                        - kms:Decrypt
                        Resource:
                            Fn::Sub: arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ssm
    EC2RoleInstanceProfile:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Path: /
            Roles:
            -   Ref: EC2Role






    SQLRole:
        Type: AWS::IAM::Role
        Properties:
            Policies:
            -   PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Action:
                        - s3:GetObject
                        Resource:
                            Fn::Sub: arn:aws:s3:::${DSS3BucketName}/${DSS3KeyPrefix}/*
                        Effect: Allow
                PolicyName: aws-deploy-sample-s3-policy
            -   PolicyName: SSM-Parameters-DomainJoin
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Effect: Allow
                        Action:
                        - ssm:GetParameter
                        - ssm:GetParameters
                        Resource:
                            Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${NamePrefix}/${DomainAdminUserName}
                    -   Effect: Allow
                        Action:
                        - ssm:DescribeParameters
                        Resource: '*'
                    -   Effect: Allow
                        Action:
                        - kms:Decrypt
                        Resource:
                            Fn::Sub: arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ssm
            -   PolicyName: SSM-Parameters-SQL
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Effect: Allow
                        Action:
                        - ssm:GetParameter
                        - ssm:GetParameters
                        Resource:
                            Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${NamePrefix}/${SQLServiceAccount}
                    -   Effect: Allow
                        Action:
                        - ssm:DescribeParameters
                        Resource: '*'
                    -   Effect: Allow
                        Action:
                        - kms:Decrypt
                        Resource:
                            Fn::Sub: arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ssm
            Path: /
            AssumeRolePolicyDocument:
                Statement:
                -   Action:
                    - sts:AssumeRole
                    Principal:
                        Service:
                        - ec2.amazonaws.com
                    Effect: Allow
                Version: 2012-10-17
    SQLProfile:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Roles:
            -   Ref: SQLRole
            Path: /



    EC2Role:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                -   Effect: Allow
                    Principal:
                        Service:
                        - ec2.amazonaws.com
                    Action:
                    - sts:AssumeRole
            Path: /
            Policies:
            -   PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Action:
                        - s3:GetObject
                        Resource:
                            Fn::Sub: arn:aws:s3:::${DSS3BucketName}/${DSS3KeyPrefix}/*
                        Effect: Allow
                PolicyName: aws-deploy-sample-s3-policy
            -   PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Action:
                        - s3:GetObject
                        Resource:
                            Fn::Sub: arn:aws:s3:::${SetupKitsS3BucketName}/${SetupKitsS3KeyPrefix}/*
                        Effect: Allow
                PolicyName: aws-setup-kits-s3-policy
            -   PolicyName: SSM-Parameters-DomainJoin
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Effect: Allow
                        Action:
                        - ssm:GetParameter
                        - ssm:GetParameters
                        Resource:
                            Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${NamePrefix}/${DomainAdminUserName}
                    -   Effect: Allow
                        Action:
                        - ssm:DescribeParameters
                        Resource: '*'
                    -   Effect: Allow
                        Action:
                        - kms:Decrypt
                        Resource:
                            Fn::Sub: arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ssm
            -   PolicyName: SSM-Parameters-PIAssetFramework
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Effect: Allow
                        Action:
                        - ssm:GetParameter
                        - ssm:GetParameters
                        Resource:
                            Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${NamePrefix}/${PIVSServiceAccountName}
                    -   Effect: Allow
                        Action:
                        - ssm:DescribeParameters
                        Resource: '*'
                    -   Effect: Allow
                        Action:
                        - kms:Decrypt
                        Resource:
                            Fn::Sub: arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ssm
    EC2RoleInstanceProfile:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Path: /
            Roles:
            -   Ref: EC2Role






    EC2Role:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                -   Effect: Allow
                    Principal:
                        Service:
                        - ec2.amazonaws.com
                    Action:
                    - sts:AssumeRole
            Path: /
            Policies:
            -   PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Action:
                        - s3:GetObject
                        Resource:
                            Fn::Sub: arn:aws:s3:::${DSS3BucketName}/${DSS3KeyPrefix}/*
                        Effect: Allow
                PolicyName: aws-deploy-sample-s3-policy
            -   PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Action:
                        - s3:GetObject
                        Resource:
                            Fn::Sub: arn:aws:s3:::${SetupKitsS3BucketName}/${SetupKitsS3KeyPrefix}/*
                        Effect: Allow
                PolicyName: aws-setup-kits-s3-policy
            -   PolicyName: SSM-Parameters-DomainJoin
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                    -   Effect: Allow
                        Action:
                        - ssm:GetParameter
                        - ssm:GetParameters
                        Resource:
                            Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${NamePrefix}/${DomainAdminUserName}
                    -   Effect: Allow
                        Action:
                        - ssm:DescribeParameters
                        Resource: '*'
                    -   Effect: Allow
                        Action:
                        - kms:Decrypt
                        Resource:
                            Fn::Sub: arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ssm
            ManagedPolicyArns:
            - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
    EC2RoleInstanceProfile:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Path: /
            Roles:
            -   Ref: EC2Role



